input {
  beats {
    port => 5044
  }
}

filter {
  if [message] =~ "^\{" {
    json {
      source => "message"
      target => ""
    }
  }
}

output {
  if [log][file][path] =~ /iec104_write\.log/ {
    elasticsearch {
      hosts => ["https://localhost:9200"]
      index => "iec104-write-%{+YYYY.MM.dd}"
      user => "elastic"
      password => "-JT2HABAmJIX8d3d9uoR"
      ssl_enabled => true
      ssl_certificate_authorities => ["/etc/logstash/certs/http_ca.crt"]
    }
  }
  else if [log][file][path] =~ /iec104_telemetry\.log/ {
    elasticsearch {
      hosts => ["https://localhost:9200"]
      index => "iec104-telemetry-%{+YYYY.MM.dd}"
      user => "elastic"
      password => "-JT2HABAmJIX8d3d9uoR"
      ssl_enabled => true
      ssl_certificate_authorities => ["/etc/logstash/certs/http_ca.crt"]
    }
  }
  else if [log][file][path] =~ /iec104_query\.log/ {
    elasticsearch {
      hosts => ["https://localhost:9200"]
      index => "iec104-query-%{+YYYY.MM.dd}"
      user => "elastic"
      password => "-JT2HABAmJIX8d3d9uoR"
      ssl_enabled => true
      ssl_certificate_authorities => ["/etc/logstash/certs/http_ca.crt"]
    }
  }
  else if [log][file][path] =~ /iec104_ctrl\.log/ {
    elasticsearch {
      hosts => ["https://localhost:9200"]
      index => "iec104-ctrl-%{+YYYY.MM.dd}"
      user => "elastic"
      password => "-JT2HABAmJIX8d3d9uoR"
      ssl_enabled => true
      ssl_certificate_authorities => ["/etc/logstash/certs/http_ca.crt"]
    }
  }
  else {
    elasticsearch {
      hosts => ["https://localhost:9200"]
      index => "ids-alerts-%{+YYYY.MM.dd}"
      user => "elastic"
      password => "-JT2HABAmJIX8d3d9uoR"
      ssl_enabled => true
      ssl_certificate_authorities => ["/etc/logstash/certs/http_ca.crt"]
    }
  }
}